### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by imbrem** [amethyst/amethyst-starter-2d#15]
So, I cloned the repo and did `cargo run`, and I get the following backtrace:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
     Running `target/debug/amethyst-starter-2d`
[INFO][amethyst::app] Initializing Amethyst...
[INFO][amethyst::app] Version: 0.13.0
[INFO][amethyst::app] Platform: x86_64-unknown-linux-gnu
[INFO][amethyst::app] Amethyst git commit: 
[INFO][amethyst::app] Rustc version: 1.43.0-nightly Nightly
[INFO][amethyst::app] Rustc git commit: dd67187965e136bff1ed05e035293441c60f0790
thread 'main' panicked at 'attempted to leave type `std::mem::ManuallyDrop<xlib_xcb::Xlib_xcb>` uninitialized, which is invalid', /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libcore/mem/mod.rs:536:5
stack backtrace:
   0:     0x5653e9d1aa64 - backtrace::backtrace::libunwind::trace::h4cef3504edb2a0a0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x5653e9d1aa64 - backtrace::backtrace::trace_unsynchronized::h7715e2e9e8e99f42
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x5653e9d1aa64 - std::sys_common::backtrace::_print_fmt::h1aa13cdff9dd64f1
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x5653e9d1aa64 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h66aca1b24836365b
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5653e9d3dd1c - core::fmt::write::h6f6121e7b92921c0
                               at src/libcore/fmt/mod.rs:1069
   5:     0x5653e9d17a03 - std::io::Write::write_fmt::h8e8dedb625e51283
                               at src/libstd/io/mod.rs:1427
   6:     0x5653e9d1d275 - std::sys_common::backtrace::_print::hb0c8e17ec030a064
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5653e9d1d275 - std::sys_common::backtrace::print::h0275567b35965425
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5653e9d1d275 - std::panicking::default_hook::{{closure}}::h38276fa010f5d6be
                               at src/libstd/panicking.rs:198
   9:     0x5653e9d1cfc2 - std::panicking::default_hook::h4e66438b12125b7c
                               at src/libstd/panicking.rs:218
  10:     0x5653e9d1d8d2 - std::panicking::rust_panic_with_hook::h71ee9cc2e920b006
                               at src/libstd/panicking.rs:511
  11:     0x5653e9d1d4bb - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x5653e9d3ba91 - core::panicking::panic_fmt::hf60a02ac680f41f0
                               at src/libcore/panicking.rs:111
  13:     0x5653e9d3b9dd - core::panicking::panic::h36de7e86ac905b71
                               at src/libcore/panicking.rs:54
  14:     0x5653e98c40e3 - core::mem::uninitialized::h176dfe8ccf61635d
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libcore/mem/mod.rs:536
  15:     0x5653e98c5392 - x11_dl::xlib_xcb::Xlib_xcb::open::h25879d89e83be9ef
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/x11-dl-2.18.3/src/link.rs:59
  16:     0x5653e96b2308 - winit::platform::platform::x11::xdisplay::XConnection::new::hf7fbb1fc9e0f3e64
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/platform/linux/x11/xdisplay.rs:39
  17:     0x5653e96f6e6f - <winit::platform::platform::X11_BACKEND as core::ops::deref::Deref>::deref::__static_ref_initialize::hfd869d1aad25a934
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/platform/linux/mod.rs:54
  18:     0x5653e96f6e6f - core::ops::function::FnOnce::call_once::h7937ab074f08e4dc
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libcore/ops/function.rs:232
  19:     0x5653e9650032 - lazy_static::lazy::Lazy<T>::get::{{closure}}::h27b3bffdcbf6e1b2
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:28
  20:     0x5653e9680415 - std::sync::once::Once::call_once::{{closure}}::ha125c663d075ac8d
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libstd/sync/once.rs:264
  21:     0x5653e9d1a148 - std::sync::once::Once::call_inner::ha6e1afc9417ec233
                               at src/libstd/sync/once.rs:416
  22:     0x5653e9680203 - std::sync::once::Once::call_once::hd2154fa1e753065b
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libstd/sync/once.rs:264
  23:     0x5653e97091e9 - lazy_static::lazy::Lazy<T>::get::hf4a4e0ebdcb6a00f
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/inline_lazy.rs:27
  24:     0x5653e97091e9 - <winit::platform::platform::X11_BACKEND as core::ops::deref::Deref>::deref::__stability::hc98e801da6b5e6cb
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/lib.rs:138
  25:     0x5653e97091e9 - <winit::platform::platform::X11_BACKEND as core::ops::deref::Deref>::deref::h3b4080c60ed6ec4a
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.3.0/src/lib.rs:140
  26:     0x5653e9708f44 - winit::platform::platform::EventsLoop::new_x11::h04217442d92f03e7
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/platform/linux/mod.rs:468
  27:     0x5653e9708bd5 - winit::platform::platform::EventsLoop::new::h7ed6a9fd901a05b5
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/platform/linux/mod.rs:449
  28:     0x5653e964fbd1 - winit::EventsLoop::new::he09cc53a3c2801d6
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.2/src/lib.rs:250
  29:     0x5653e94e018f - <amethyst_window::bundle::WindowBundle as amethyst_core::bundle::SystemBundle>::build::hf909ad02d18d87aa
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_window-0.3.0/src/bundle.rs:56
  30:     0x5653e91a8d3d - <amethyst_rendy::plugins::window::RenderToWindow as amethyst_rendy::bundle::RenderPlugin<B>>::on_build::hac8d11fd07bc2219
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_rendy-0.3.0/src/plugins.rs:80
  31:     0x5653e8e014a2 - <amethyst_rendy::bundle::RenderingBundle<B> as amethyst_core::bundle::SystemBundle>::build::hb4b1d75e8963a451
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_rendy-0.3.0/src/bundle.rs:92
  32:     0x5653e8db36cf - <amethyst_core::deferred_dispatcher_operation::AddBundle<B> as amethyst_core::deferred_dispatcher_operation::DispatcherOperation>::exec::h3e6f01f4815a8d94
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst_core-0.8.0/src/deferred_dispatcher_operation.rs:175
  33:     0x5653e923fb33 - <amethyst::game_data::GameDataBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build::{{closure}}::h1cf0066e5644e913
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.0/src/game_data.rs:473
  34:     0x5653e923ae32 - core::iter::traits::iterator::Iterator::try_for_each::call::{{closure}}::h949c423d681b60e9
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libcore/iter/traits/iterator.rs:1919
  35:     0x5653e923c72b - core::iter::traits::iterator::Iterator::try_fold::h2eda26de85656564
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libcore/iter/traits/iterator.rs:1877
  36:     0x5653e923c613 - core::iter::traits::iterator::Iterator::try_for_each::hecbc42f05d175a37
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libcore/iter/traits/iterator.rs:1922
  37:     0x5653e923f83b - <amethyst::game_data::GameDataBuilder as amethyst::game_data::DataInit<amethyst::game_data::GameData>>::build::h02dfda26232fd4a1
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.0/src/game_data.rs:470
  38:     0x5653e91647cb - amethyst::app::ApplicationBuilder<S,T,E,X>::build::h616e3a9c40d4e1ea
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.0/src/app.rs:894
  39:     0x5653e91625e1 - amethyst::app::CoreApplication<T,E,R>::new::h3d9d1ab96b38fab6
                               at /home/tekne/.cargo/registry/src/github.com-1ecc6299db9ec823/amethyst-0.13.0/src/app.rs:201
  40:     0x5653e9135a7d - amethyst_starter_2d::main::h2116cf6171fef805
                               at src/main.rs:33
  41:     0x5653e91a908b - std::rt::lang_start::{{closure}}::hb811ac8de2469d63
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libstd/rt.rs:67
  42:     0x5653e9d1de6f - std::rt::lang_start_internal::{{closure}}::h899784560c039022
                               at src/libstd/rt.rs:52
  43:     0x5653e9d1de6f - std::panicking::try::do_call::h4cca0c86a0d15768
                               at src/libstd/panicking.rs:331
  44:     0x5653e9d1de6f - std::panicking::try::h0144d03dae575185
                               at src/libstd/panicking.rs:274
  45:     0x5653e9d1de6f - std::panic::catch_unwind::h94eb01a0210545cc
                               at src/libstd/panic.rs:394
  46:     0x5653e9d1de6f - std::rt::lang_start_internal::h5cf5d241f7b37797
                               at src/libstd/rt.rs:51
  47:     0x5653e91a9067 - std::rt::lang_start::h24779d6aac3af2a3
                               at /rustc/dd67187965e136bff1ed05e035293441c60f0790/src/libstd/rt.rs:67
  48:     0x5653e9135f0a - main
  49:     0x7f80d37e21e3 - __libc_start_main
  50:     0x5653e8da11be - _start
  51:                0x0 - <unknown>
```
I downloaded all the dependencies instructed. Release mode doesn't help.

**Comment by happenslol** [comment]
Hi,
I've just merged an update to the newest Amethyst version. Could you try the newest version and report back if the same crash occurs?

**Comment by luciusmagn** [comment]
I had the same issue just a few minutes ago. `cargo update --aggressive` seems to have fixed the problem on both release and dev mode

**Comment by steveruizok** [comment]
> I had the same issue just a few minutes ago. `cargo update --aggressive` seems to have fixed the problem on both release and dev mode

This fixed my problems on a clean attempt at following the README.
